apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test-pod
  name: test-pod
spec:
  containers:
  - image: floci/floci:latest
    name: test-pod
    ports:
    - containerPort: 4566
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
